name: fitness_trainer_app
description: "A fitness trainer app that uses custom model for workout detection"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  http: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 